#!/usr/bin/env bash
# Rebuild docs/reference/catalog.md by scanning frontmatter of all knowledge notes.
# Installed to product repo at scripts/rebuild-catalog.sh by `facio-superpowers init`.
# Usage: scripts/rebuild-catalog.sh [--root <dir>] [--out <file>]

set -euo pipefail

ROOT="docs/reference"
OUT="$ROOT/catalog.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="$2"; shift 2 ;;
    --out)  OUT="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

extract_field() {
  local file="$1" field="$2"
  awk -v f="$field" '
    /^---$/ { in_fm = !in_fm; next }
    in_fm && $0 ~ "^" f ":" { sub("^" f ":[[:space:]]*", ""); print; exit }
  ' "$file"
}

# §C.4 schema: 7 REQUIRED (id/type/title/maturity/ref_count/created/source) + 2 OPTIONAL (tags/last_referenced).
# Codex review Round 1 MUST FIX #2 + #3: tags/last_referenced 实际是 OPTIONAL；id 必须匹配 K-<type>-<NNN> 3 位 zero-padded format.

validate_note_schema() {
  local file="$1"
  local missing=""

  # REQUIRED fields (7)
  for field in id type title maturity ref_count created source; do
    grep -qE "^${field}:" "$file" || missing="${missing} ${field}"
  done
  if [[ -n "$missing" ]]; then
    echo "✗ schema invalid: $file missing REQUIRED fields:$missing" >&2
    return 1
  fi

  local id_val maturity_val type_val rc_val id_type_prefix lr_val

  # ID format (REQUIRED + regex)
  id_val=$(extract_field "$file" "id")
  if ! [[ "$id_val" =~ ^K-(decisions|guidelines|pitfalls|model|process)-[0-9]{3}$ ]]; then
    echo "✗ $file id violates K-<type>-<NNN> 3-digit zero-padded format: '$id_val'" >&2
    return 1
  fi

  maturity_val=$(extract_field "$file" "maturity")
  case "$maturity_val" in
    draft|verified|proven) ;;
    *) echo "✗ $file maturity must be draft|verified|proven (got: '$maturity_val')" >&2; return 1 ;;
  esac

  type_val=$(extract_field "$file" "type")
  case "$type_val" in
    decision|guideline|pitfall|model|process) ;;
    *) echo "✗ $file type invalid: '$type_val'" >&2; return 1 ;;
  esac

  # ID prefix must align with type (decisions↔decision, etc.)
  id_type_prefix=$(echo "$id_val" | awk -F- '{print $2}')
  case "$type_val:$id_type_prefix" in
    decision:decisions|guideline:guidelines|pitfall:pitfalls|model:model|process:process) ;;
    *) echo "✗ $file id prefix ($id_type_prefix) does not match type ($type_val)" >&2; return 1 ;;
  esac

  rc_val=$(extract_field "$file" "ref_count")
  if ! [[ "$rc_val" =~ ^[0-9]+$ ]]; then
    echo "✗ $file ref_count not integer: '$rc_val'" >&2
    return 1
  fi

  # OPTIONAL: last_referenced — if present, must be YYYY-MM-DD or empty
  if grep -qE "^last_referenced:" "$file"; then
    lr_val=$(extract_field "$file" "last_referenced")
    if [[ -n "$lr_val" ]] && ! [[ "$lr_val" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
      echo "✗ $file last_referenced not YYYY-MM-DD: '$lr_val'" >&2
      return 1
    fi
  fi

  return 0
}

validate_all_notes() {
  local errors=0
  shopt -s nullglob
  for type_dir in decisions guidelines pitfalls; do
    for f in "$ROOT/$type_dir"/*.md; do
      [[ "$(basename "$f")" == "README.md" ]] && continue
      validate_note_schema "$f" || errors=$((errors + 1))
    done
  done
  shopt -u nullglob
  if [[ $errors -gt 0 ]]; then
    echo "✗ rebuild-catalog.sh aborted: $errors note(s) failed schema validation" >&2
    exit 1
  fi
}

render_section() {
  local type_dir="$1"
  local found=0
  shopt -s nullglob
  for f in "$ROOT/$type_dir"/*.md; do
    [[ "$(basename "$f")" == "README.md" ]] && continue
    local id title maturity ref_count tags rel_path
    id=$(extract_field "$f" "id")
    title=$(extract_field "$f" "title")
    maturity=$(extract_field "$f" "maturity")
    ref_count=$(extract_field "$f" "ref_count")
    tags=$(extract_field "$f" "tags" | tr -d '[]')
    rel_path="./${type_dir}/$(basename "$f")"
    echo "- [${id}](${rel_path}) — ${title} · ${maturity} · ref_count: ${ref_count} · tags: ${tags}"
    found=1
  done
  shopt -u nullglob
  if [[ $found -eq 0 ]]; then
    echo "_(空 · M3 起累积)_"
  fi
}

validate_all_notes

cat > "$OUT" <<'HEADER'
<!-- AUTO-GENERATED by scripts/rebuild-catalog.sh; do not edit by hand -->
# Knowledge Catalog

> Single source of truth for `docs/reference/{decisions,guidelines,pitfalls}/` lookup.
> Host spec workflows 从这里加载相关 notes（progressive disclosure 入口）。
>
> AI 永远读 catalog，**不扫目录**。

## Decisions

HEADER

render_section "decisions" >> "$OUT"

cat >> "$OUT" <<'MID1'

## Guidelines

MID1

render_section "guidelines" >> "$OUT"

cat >> "$OUT" <<'MID2'

## Pitfalls

MID2

render_section "pitfalls" >> "$OUT"

{
  echo ""
  echo "---"
  echo ""
  echo "**Last rebuild:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
} >> "$OUT"

echo "Rebuilt: $OUT"
